name: Tag

on:
    push:
        branches: ["main"]
        paths:
            - "**.go"
            - "**.c"
            - "**.cc"
            - "**.h"
    workflow_dispatch:

permissions:
    contents: write
    id-token: write

concurrency:
    group: tag
    cancel-in-progress: true

jobs:
    tag:
        environment:
            name: github-pages
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Tag new version
            run: |
              git config --global user.email "actions@github.com"
              git config --global user.name "GitHub Actions"
              tagname="$(date +%s)"
              git tag -a $tagname -m "Release $tagname"
              git push origin $tagname
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/Frank-Mayer/sv2-types/releases \
              -d '{"tag_name":"'"$tagname"'","name":"'"$tagname"'","draft":false,"prerelease":false,"generate_release_notes":false}'
